### ISSUE TITLE
show-paren-mode hard to distinguish between balanced and imbalanced parens

### ISSUE THREAD

**Issue by ccann** [john2x/flatui-theme.el#7]
Hey! FIrst off thank you so much for this theme!

I use `show-paren-mode` and when it changes the background face on matching parens it uses the same color as for the background face of an unmatched paren, the only difference being the foreground.

`show-paren-mode`: balanced parens

<img width="249" alt="screen shot 2016-02-15 at 9 31 34 am" src="https://cloud.githubusercontent.com/assets/2650566/13051474/689d87f4-d3c7-11e5-9873-1880a71017cd.png">

`show-paren-mode`: imbalanced parens

<img width="251" alt="screen shot 2016-02-15 at 9 31 43 am" src="https://cloud.githubusercontent.com/assets/2650566/13051476/6a2db36e-d3c7-11e5-83df-e0ee67ec9a9b.png">

It's often hard to distinguish between them so I thought I might ask if there was a reason you chose red as the background color for the balanced parens? Obviously I can change the color on my end but I figured others could have the same opinion so it would be worth a discussion. Thanks!

**Comment by john2x** [comment]
Fixed with 4c9c7bc. Thanks!
